name: Sandbox CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Uzak Sunucuya SSH ile Bağlan ve Docker'ı Güncelle
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd ~/DotNetDockerPublishTria
          
          # 1. Sunucudaki Git geçmişini temizle ve main branch'ine zorla eşitle
          git fetch origin main
          git reset --hard origin/main
          
          # 2. Sudo komutlarını SSH oturumundaki şifre ile besleyerek çalıştır
          echo "POSTGRES_USER=postgres" > .env
          echo "POSTGRES_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "POSTGRES_DB=todosdb" >> .env

          # 3. Eski veritabanı kalıntılarını sil (-v) ve sistemi ayağa kaldır
          echo "${{ secrets.SSH_PASSWORD }}" | sudo -S docker compose down -v
          echo "${{ secrets.SSH_PASSWORD }}" | sudo -S docker compose build --no-cache
          echo "${{ secrets.SSH_PASSWORD }}" | sudo -S docker compose up -d --force-recreate 